name: CI
on:
   # События, которые запускают jobs
    push:
      branches: [ "main" ]
  
jobs:
    # Название job вы можете назвать как угодно
    my_build_job:
      runs-on: ubuntu-latest
        # Шаги
        steps:
          - name: Checkout
            # Actions от github: проверяет репозиторий, гит и т.д.
            uses: actions/checkout@v3
          - name: Set up Node
            uses: actions/setup-node@v3
            with:
              node-version: 18
              cache: 'npm'
          - name: Install dependencies
            run: npm install
          - name: Build
            run: npm run build